Update build-and-test.yml

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -78,90 +78,95 @@ jobs:
             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
 
   update-code-version:
-   runs-on: ubuntu-latest
-   needs: [build-and-test-with-cache]
+    runs-on: ubuntu-latest
+    needs: [build-and-test-with-cache]
 
-   steps:
-        - name: Check for new commits
-          id: check_commits
-          run: |
-            echo "Checking for new commits since the last tag..."
-            LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
-            if [ "$LAST_TAG" = "0.0.0" ]; then
-              echo "No previous tags found."
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Check for new commits
+        id: check_commits
+        run: |
+          echo "Checking for new commits since the last tag..."
+          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
+          if [ "$LAST_TAG" = "0.0.0" ]; then
+            echo "No previous tags found."
+            echo "new_commits=true" >> $GITHUB_ENV
+          else
+            NEW_COMMITS=$(git log $LAST_TAG..HEAD --oneline)
+            if [ -z "$NEW_COMMITS" ]; then
+              echo "No new commits since the last tag."
+              echo "new_commits=false" >> $GITHUB_ENV
+            else
+              echo "New commits found."
               echo "new_commits=true" >> $GITHUB_ENV
-            else
-              NEW_COMMITS=$(git log $LAST_TAG..HEAD --oneline)
-              if [ -z "$NEW_COMMITS" ]; then
-                echo "No new commits since the last tag."
-                echo "new_commits=false" >> $GITHUB_ENV
-              else
-                echo "New commits found."
-                echo "new_commits=true" >> $GITHUB_ENV
-              fi
             fi
-  
-        - name: Bump version and set env
-          id: tag_version
-          if: env.new_commits == 'true'
-          run: |
-            echo "Bumping version..."
-            git config --global --add safe.directory /github/workspace
-            DEFAULT_BUMP="patch"
-            LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
-            if [ "$LAST_TAG" = "0.0.0" ]; then
-              NEW_TAG="0.0.1"
-            else
-              IFS='.' read -r -a TAG_PARTS <<< "$LAST_TAG"
-              MAJOR=${TAG_PARTS[0]}
-              MINOR=${TAG_PARTS[1]}
-              PATCH=${TAG_PARTS[2]}
-              PATCH=$((PATCH + 1))
-              NEW_TAG="$MAJOR.$MINOR.$PATCH"
-            fi
-            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
-  
-        - name: Verify update-version.cjs existence
-          if: env.new_commits == 'true'
-          run: |
-            if [ ! -f update-version.cjs ]; then
-              echo "update-version.cjs not found!"
-              exit 1
-            fi
+          fi
 
-        - name: Update package.json and package-lock.json
-          if: env.new_commits == 'true'
-          run: node update-version.cjs ${{ env.NEW_TAG }}
-  
-        - name: Commit updated version files
-          if: env.new_commits == 'true'
-          run: |
-            echo "Committing updated version files..."
-            git config --local user.email "action@github.com"
-            git config --local user.name "GitHub Action"
-            git add package.json package-lock.json
-            git commit -m "Update version to $NEW_TAG"
-  
-        - name: Pull changes from main branch
-          if: env.new_commits == 'true'
-          run: |
-            echo "Pulling changes from main branch..."
-            git config pull.ff only
-            git pull origin main
-  
-        - name: Push changes
-          if: env.new_commits == 'true'
-          run: |
-            echo "Pushing changes to main branch..."
-            git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/quarks-team/projeto_integrador_tecsus_frontend.git main
-  
-        - name: Store Status Check
-          id: store_status_check
-          run: echo "true" > status_check.txt
-          if: ${{ always() }}
-  
-        - name: Upload Status Check File
-          uses: actions/upload-artifact@v3
-          with:
-            name: status-check
-            path: status_check.txt
+      - name: Bump version and set env
+        id: tag_version
+        if: env.new_commits == 'true'
+        run: |
+          echo "Bumping version..."
+          git config --global --add safe.directory /github/workspace
+          DEFAULT_BUMP="patch"
+          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
+          if [ "$LAST_TAG" = "0.0.0" ]; then
+            NEW_TAG="0.0.1"
+          else
+            IFS='.' read -r -a TAG_PARTS <<< "$LAST_TAG"
+            MAJOR=${TAG_PARTS[0]}
+            MINOR=${TAG_PARTS[1]}
+            PATCH=${TAG_PARTS[2]}
+            PATCH=$((PATCH + 1))
+            NEW_TAG="$MAJOR.$MINOR.$PATCH"
+          fi
+          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
+
+      - name: Verify update-version.cjs existence
+        if: env.new_commits == 'true'
+        run: |
+          if [ ! -f update-version.cjs ]; then
+            echo "update-version.cjs not found!"
+            exit 1
+          fi
+
+      - name: Update package.json and package-lock.json
+        if: env.new_commits == 'true'
+        run: node update-version.cjs ${{ env.NEW_TAG }}
+
+      - name: Commit updated version files
+        if: env.new_commits == 'true'
+        run: |
+          echo "Committing updated version files..."
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add package.json package-lock.json
+          git commit -m "Update version to $NEW_TAG"
+
+      - name: Pull changes from main branch
+        if: env.new_commits == 'true'
+        run: |
+          echo "Pulling changes from main branch..."
+          git config pull.ff only
+          git pull origin main
+
+      - name: Push changes
+        if: env.new_commits == 'true'
+        run: |
+          echo "Pushing changes to main branch..."
+          git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/quarks-team/projeto_integrador_tecsus_frontend.git main
+
+      - name: Store Status Check
+        id: store_status_check
+        run: echo "true" > status_check.txt
+        if: ${{ always() }}
+
+      - name: Upload Status Check File
+        uses: actions/upload-artifact@v3
+        with:
+          name: status-check
+          path: status_check.txt
