Update build-and-test.yml

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -86,6 +86,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
+
+      - name: Verify update-version.js existence
+        run: |
+          if [ ! -f update-version.js ]; then
+            echo "update-version.js not found!"
+            exit 1
+          fi
           
       - name: Update package.json and package-lock.json
         run: node update-version.js ${{ steps.tag_version.outputs.new_tag }}
